version: "3.9"
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: automation
  #   ports:
  #     - 3000:8085
  postgres:
    image: postgres:12-alpine
    environment:
      - name=value
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=new-app
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:admin123@postgres:2022/new-app?sslmode=disable
